### ISSUE TITLE
Add public way to clear subscribers?

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/pulsar#17]
I'm working on wrapping specs in transactions. I'm using a Pulsar event to run code whenever a new database connection is created. The problem is that there are situations where I would like to be able to clear all the subscribers:
- I'll be calling subscribe for every spec and I don't want multiple subscribers so I clear afterwards
- In situations where I don't want to do the transaction code, I want to clear the subscriber if it exists

Would it make sense to add a public `Pulsar::Event.clear` to clear any subscribers? Don't know if that's a good name for it (I used `clear_subscribers` in my code)

Reference: https://github.com/luckyframework/avram/pull/780

**Comment by jwoertink** [comment]
I think I needed to do that too at one point, but I forget why. I like `clear_subscribers`, it reads well.
